variable "env" {}
variable "subnet_azs" {}
variable "default_vpc_cidr_block" {}
variable "default_vpc_id" {}
variable "default_route_table" {}
variable "public_subnet_cidr_block" {}
variable "app_subnet_cidr_block" {}
variable "db_subnet_cidr_block" {}
variable "vpc_cidr_block" {}